export const Icons = {
  earPhone: require('./ear_phone.png'),
  notification: require('./notification.png'),
  timeIcon: require('./time_icon.png'),
  calendarCheck: require('./calendar_check.png'),
  arrowIcon: require('./arrow_icon.png'),

  orderMedicine: require('./order_medicine.png'),
  icuInstallationIcon: require('./icu_installation_icon.png'),
  doctorConsultation: require('./doctor_consultation.png'),
  physiotherapyIcon: require('./physiotherapy_icon.png'),
  disgnosticsIcon: require('./disgnostics_icon.png'),
  nursingIcon: require('./nursing_icon.png'),
  termAndCondition: require('./term_and_condition.png'),
  logOutIcon: require('./log_out_icon.png'),
  googleMaps: require('./google-maps.png'),

  noInternate: require('./no_Internate.png'),
  views: require('./views.png'),
  dislikeIcon: require('./dislike_icon.png'),
  likeFill: require('./like_fill.png'),
  gallaryIcon: require('./gallary_icon.png'),
  chatIcon: require('./chat_icon.png'),
  plusIcon: require('./plus_icon.png'),
  editIcon: require('./edit_icon.png'),
  userOutlineIcon: require('./user_outline_icon.png'),

  editUser: require('./edit_user.png'),
  eMail: require('./e_mail.png'),
  phoneIcon: require('./phone_icon.png'),
  mapIcon: require('./map_icon.png'),
  cartIcon: require('./cart_icon.png'),
  eMailLight: require('./e_mail_light.png'),
  calenderIcon: require('./calender_icon.png'),
  clockIcon: require('./clock_icon.png'),
  copunIcon: require('./copun_icon.png'),

  closeIcon: require('./close_icon.png'),
  varifiedFillIcon: require('./varified_fill_icon.png'),
  varifiedOutlineIcon: require('./varified_outline_icon.png'),
  googleIcon: require('./google_icon.png'),
  masterCardIcon: require('./master_card_icon.png'),
  visaCardicon: require('./visa_card_icon.png'),
  phonepeIcon: require('./phonepe_icon.png'),
  paytemIcon: require('./paytem_icon.png'),
  creditCradIcon: require('./credit_crad_icon.png'),
  downLoadIcon: require('./down_load_icon.png'),
  questionMarkIcon: require('./question_mark_icon.png'),
  locationIcon: require('./location_icon.png'),
  headerOutlineIcon: require('./header_outline_icon.png'),

  // product details
  scheduleIcon: require('./schedule_icon.png'),
  returnBoxIcon: require('./return_box_icon.png'),
  cashonDeliberyIcon: require('./cashon_delibery_icon.png'),
  deleteIcon: require('./delete_icon.png'),
  upDownIcon: require('./up_down_icon.png'),
  orderIcon: require('./order_icon.png'),

  // latest new
  mobileRechargeIcon: require('./mobile_recharge_icon.png'),
  userIcon: require('./user_icon.png'),
  passwordIcon: require('./password_icon.png'),
  showPasswordIcon: require('./show_password_icon.png'),
  hidePasswordIcon: require('./hide_password_icon.png'),
  operatorIcon: require('./operator.png'),
  stateIcon: require('./state_icon.png'),
  amountIcon: require('./amount_icon.png'),
  ruppersIcon: require('./ruppers_icon.png'),
  nextIcon: require('./next_icon.png'),

  dthRechargeIcon: require('./dth_recharge_icon.png'),
  fastTagIcon: require('./fast_tag_icon.png'),
  drawerIcon: require('./drawer_icon.png'),

  // finacial services
  AepeIcon: require('./aep_icon.png'),
  dmtIcon: require('./dmt_icon.png'),
  payOutIcon: require('./pay_out_icon.png'),

  // ticket icon
  trainIcon: require('./train_icon.png'),
  busIcon: require('./bus_icon.png'),
  hotelIcon: require('./hotel_icon.png'),
  planeIcon: require('./plane_icon.png'),

  // ticket icon
  // electricityIcon: require('./electricity_icon.png'),
  // broadbandIcon: require('./broadband_icon.jpeg'),
  usbCableIcon: require('./usb_cable_icon.png'),
  gasCylinderIcon: require('./gas_cylinder_icon.png'),
  faildIcon: require('./faild_icon.png'),
  walletIcon: require('./wallet_icon.png'),

  // fastagIcon: require('./fastag_icon.png'),

  // bill payment icon
  creditCardsIcon: require('./credit_cards_icon.png'),
  donationIcon: require('./donation_icon.png'),
  hospitalIcon: require('./hospital_icon.png'),
  housingSocietyIcon: require('./housing_society_icon.png'),
  insuranceIcon: require('./insurance_icon.png'),
  educationFeeIcon: require('./education_fee_icon.png'),
  landlinePostpaidIcon: require('./landline_postpaid_icon.png'),
  loanRepaymentIcon: require('./loan_repayment_icon.png'),
  mobilePrepaidIcon: require('./mobile_prepaid_icon.png'),
  rentalIcon: require('./rental_icon.png'),
  subscribeIcon: require('./subscribe_icon.png'),
  downArrowIcon: require('./down_arrow_icon.png'),
  peopleIcon: require('./people_icon.png'),

  //  servicerIcon

  banckofIndiaIcon: require('./banck_of_india_icon.png'),
  indianBankIcon: require('./indian_bank_icon.png'),
  caneraBankIcon: require('./canera_bank_icon.png'),
  checkIcon: require('./check_icon.png'),
  fildIcon: require('./close.png'),
  downloadIcon: require('./download_icon.png'),
  repeatIcon: require('./repeat_icon.png'),
  fingerprintIcon: require('./fingerprint_icon.png'),

  // operatpor icon
  airtelIcon: require('./airtel_icon.png'),
  viLogoIcon: require('./vi_logo_icon.png'),
  bsnlLogo: require('./bsnl_logo.png'),

  //profile
  userFillIcon: require('./user_fill_icon.png'),
  kycIcon: require('./kyc_icon.png'),
  transactionIcon: require('./transaction_icon.png'),
  couponIcon: require('./coupon_icon.png'),
  referAndEarnIcon: require('./referAndEarn_icon.png'),
  showIcon: require('./show_icon.png'),

  // static icon
  broadbandIcon: require('./static/broadband.png'),
  electricityIcon: require('./static/electricity.png'),
  cabletvIcon: require('./static/cabletv.png'),
  clubandassociationIcon: require('./static/clubandassociation.png'),
  creditcard: require('./static/creditcard.png'),
  donation: require('./static/donation.png'),
  dth: require('./static/dth.png'),
  educationfees: require('./static/educationfees.png'),
  fastag: require('./static/fastag.png'),
  gas: require('./static/gas.png'),
  hospital: require('./static/hospital.png'),
  hospitalandpathology: require('./static/hospitalandpathology.png'),
  housingsocietyss: require('./static/housingsocietyss.png'),
  insurans: require('./static/insurans.png'),
  landlinepostpaidss: require('./static/landlinepostpaidss.png'),
  loanrepayment: require('./static/loanrepayment.png'),
  Lpggas: require('./static/Lpggasss.png'),
  mobilepostpaid: require('./static/mobilepostpaid.png'),
  mobilrprepaidss: require('./static/mobilrprepaidss.png'),
  municipalservices: require('./static/municipalservices.png'),
  ncmcss: require('./static/ncmcss.png'),
  recurringdeposit: require('./static/recurringdeposit.png'),
  rentalss: require('./static/rentalss.png'),
  subscription: require('./static/subscription.png'),
  water: require('./static/water.png'),
  panCardIcon: require('./panCard_icon.png'),
  AadharCardIcon: require('./AadharCard_icon.png'),

  // tost icon
  successIcon: require('./success_icon.png'),
  infoIcon: require('./info_icon.png'),
  cancelIcon: require('./cancel_icon.png'),
  listIcon: require('./list_icon.png'),
};
